### ISSUE TITLE
bad link for default values yaml

### ISSUE THREAD

**Issue by ChrisThePCGeek** [techno-tim/launchpad#12]
https://gitlab.com/gitlab-org/charts/gitlab-runner/blob/master/values.yaml

this link is bad for the default values for gitlab-runner

I believe this is the correct link: (looks like they went from master to "main"
https://gitlab.com/gitlab-org/charts/gitlab-runner/blob/main/values.yaml

**Comment by timothystewart6** [comment]
thank you!

**Comment by timothystewart6** [comment]
Thank you, fixed!
